{
 "title": "6. summary_of_operating_system_status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current active viewers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "__auto" },
    {
     "expr": "100 * (node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "__auto" },
    {
     "expr": "100 * (node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "swap status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "__auto" },
    {
     "expr": "100 * (node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "memory status",
   "type": "piechart",
   "description": "The size in bytes of process memory. This includes call stack, heap, and internal structures.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "__auto"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" },
    {
     "expr": "100 * (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "system  uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "system boot time",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 26 },
   "targets": [
    { "expr": "node_boot_time_seconds", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "system load status",
   "type": "barchart",
   "description": "Time since the collect of data by Hardware Sentry was first started.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load5", "legendFormat": "__auto" },
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "running/blocked_process",
   "type": "gauge",
   "description": "The size in bytes of process memory. This includes call stack, heap, and internal structures.",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_procs_blocked", "legendFormat": "__auto" },
    { "expr": "node_procs_running", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "systemfiles",
   "type": "stat",
   "description": "The temperature sensors reporting the highest temperatures at the moment.\n\nClick on a temperature for details.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "node_filesystem_files_free", "legendFormat": "__auto" },
    { "expr": "node_filesystem_files", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "disk_in/out",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}