{
 "title": "9. the_amount_of_hard_drive_usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "momentary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "description": "SSL Certificate Monitoring Table. On the first column you can find the SSL x509 Certificate name, and on the second column the TTL/Expirty Date in days.\n\nThresholds are:\n* From 0 days to 14, Red\n* From 15 days to 30, Orange\n* From 31 days onward, Green",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$ssl_name",
   "type": "stat",
   "description": "SSL Certificate Monitoring Stat. On the Title of the widget you can find the SSL Certificate name, and on the value the current TTL/Expiry date in days.\n\nThresholds are:\n* From 0 days to 14, Red\n* From 15 days to 30, Orange\n* From 31 days onward, Green",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "repeat": "ssl_name",
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[5m])) by (device)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "5 minutes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[5m])) by (device)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "10 minutes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": " usage ( container number ) password CPU Request Rate ( overall 100%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[10m])) by (device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[10m])) by (device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod View more dashboards ( Memory Usage )",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[10m])) by (device)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "15 minutes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[15m])) by (device)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "all", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "hard drive usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[1m])) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[5m])) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[5m])) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[10m])) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[15m])) by (device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Resource comprehensive display ",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[1m])) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[5m])) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[5m])) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[10m])) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[15m])) by (device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Resource comprehensive display ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[1m])) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[5m])) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[5m])) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[10m])) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[15m])) by (device)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}