{
 "title": "16. online_ofline_statuse_of_the_page",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "momentary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Replica Query Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Available Connections",
     "type": "stat",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox\"}"
      }
     ]
    },
    {
     "title": "Disk Writes Completed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 10, "y": 9 },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "day",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Connections",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 20, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(probe_success{job=\"blackbox\"}[1d])"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "avg_over_time(probe_success{job=\"blackbox\"}[1d])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg_over_time(probe_success{job=\"blackbox\"}[1d])",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Connections",
     "type": "stat",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg_over_time(probe_success{job=\"blackbox\"}[30d])"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "avg_over_time(probe_success{job=\"blackbox\"}[30d])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "year",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(probe_success{job=\"blackbox\"}[365d])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(probe_success{job=\"blackbox\"}[365d])"
      }
     ]
    }
   ]
  },
  {
   "title": "online_ofline_statuse_of_the_page",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[1d])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[30d])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[365d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[1d])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[30d])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[365d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[1d])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[30d])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[365d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[1d])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[30d])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[365d])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}